name: '🤖 Jules Agent PR Generator'

on:
  issues:
    types: [labeled]

jobs:
  label-added:
    if: github.event.label.name == 'bug' || github.event.label.name == 'enhancement' || github.event.label.name == 'documentation'
    
    runs-on: ubuntu-latest
    steps:
      - name: Call JULES API to Create PR
        env:
          JULES_PAYLOAD: |
            ${{ toJSON({
                prompt: 'Please create a new pull request to implement the feature or fix the bug described in the issue below.\n\nIssue Title: ' + github.event.issue.title + '\n\nIssue Body:\n' + github.event.issue.body,
                sourceContext: {
                  source: 'sources/github/' + github.repository,
                  githubRepoContext: {
                    startingBranch: github.event.repository.default_branch
                  }
                },
                automationMode: 'AUTO_CREATE_PR',
                title: 'JULES PR for Issue #' + github.event.issue.number + ': ' + github.event.issue.title
              })
            }}

        run: |
          echo "Sending this payload to JULES:"
          echo "$JULES_PAYLOAD"

          curl -X POST 'https://jules.googleapis.com/v1alpha/sessions' \
          -H "Content-Type: application/json" \
          -H "X-Goog-Api-Key: ${{ secrets.JULES_API }}" \
          -d "$JULES_PAYLOAD"
